version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=todo4
    ports:
      - 3306:3306
    volumes:
      - contact-manager-mysql-data:/var/lib/mysql
      - contact-manager-mysql-config:/etc/mysql

backend:
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  environment:
    MYSQL_DBNAME: todo4
    MYSQL_USER: root
    MYSQL_PASSWORD: 123123
    MYSQL_HOST: db
  volumes:
    - ./:/nodejs_hello
  ports:
    - "3030:3030"
  depends_on:
    - db

volumes:
  contact-manager-mysql-data:
  contact-manager-mysql-config:
